### ISSUE TITLE
Running `pip install -e .` as documented fails

### ISSUE THREAD

**Issue by asartalo** [Open-Book-Genome-Project/TheBestBookOn.com#3]
Running `pip install -e .` as documented fails with the error message:

```
    ERROR: Command errored out with exit status 1:
     command: [REDACTED]/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'[REDACTED]/TheBestBookOn.com/setup.py'"'"'; __file__='"'"'[REDACTED]/TheBestBookOn.com/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jxvksy1r
         cwd: [REDACTED]/TheBestBookOn.com/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "[REDACTED]/TheBestBookOn.com/setup.py", line 42, in <module>
        long_description=read('README.rst'),
      File "[REDACTED]/TheBestBookOn.com/setup.py", line 27, in read
        return codecs.open(os.path.join(here, *parts), 'r').read()
      File "[REDACTED]/3.8.2/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '[REDACTED]/TheBestBookOn.com/README.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

On setup.py, `README.rst` should probably be `README.md`.

Also, the instructions say to run the command `cd /bestbook` but, it might be in my environment (Ubuntu 20.04) but the directory I have on the project after running `pip install` was `bestook.egg-info/` with the following contents:

```
dependency_links.txt
PKG-INFO
requires.txt
SOURCES.txt
top_level.txt
```
I'm new to python so I don't know how to move forward from this.

**Comment by asartalo** [comment]
Scratch the last part about  `bestbook`. I was being dumb. :)
