### ISSUE TITLE
Encountered SQLAlchemy TimeoutError while using the site

### ISSUE THREAD

**Issue by jamesachamp** [Open-Book-Genome-Project/TheBestBookOn.com#47]
Error page with stack trace appeared after submitting a recommendation and navigating to the admin page.  We may want to reconfigure SQLAlchemy before inviting folks to use the site.

Full stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/var/www/TheBestBookOn.com/bestbook/views/__init__.py", line 49, in inner
    return f(*args, **kwargs)
  File "/var/www/TheBestBookOn.com/bestbook/views/__init__.py", line 306, in get
    return render_template("base.html", template="admin.html", models=models)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/var/www/TheBestBookOn.com/bestbook/templates/base.html", line 60, in top-level template code
    {% include template %}
  File "/var/www/TheBestBookOn.com/bestbook/templates/admin.html", line 13, in top-level template code
    {% set recommendations = models['recommendations'].all() -%}
  File "/var/www/TheBestBookOn.com/bestbook/api/core.py", line 85, in all
    return cls.query.all()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3346, in all
    return list(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3530, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3545, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3523, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1141, in connection
    execution_options=execution_options,
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 1147, in _connection_for_bind
    engine, execution_options
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2304, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2338, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool/impl.py", line 132, in _do_get
    code="3o7r",
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)
```

**Comment by jamesachamp** [comment]
I encountered this error again whilst trying to open a book notes modal in Open Library.

**Comment by cclauss** [comment]
> python3.5

Why is the server running on an expired version of Python?  Do we get similar results on a current Python?
* https://devguide.python.org/#status-of-python-branches
* https://devguide.python.org/devcycle/#end-of-life-branches

**Comment by jamesachamp** [comment]
I agree that we should be using a newer version of Python, but I suspect that the root of this issue is poor session management.  It looks like there are many instances where sessions are not closed at the end of transactions.  This eventually leads to a pool full of connections that need to be freed. 

I'll do a more in-depth analysis and work on correcting this within the next few days.

**Comment by jamesachamp** [comment]
Just encountered this error again.  It looks like connections are being freed, as the page rendered normally on refresh.  I was able to quickly trigger the error again by opening three tabs and navigating to different pages on the site.

Here's some things that we could do to in support of closing this issue again:
- Increase the pool size and max overflow from the default (5 and 10, respectively).  This should probably be done before the MVP anyway...
- Simplify complicated transactions.  The admin approval queries are especially bad, and should probably utilize eager loading of related objects instead of multiple queries.
- Set up profiling for SQLAlchemy transactions.
- Implement caching.

I suspect that things will run more smoothly after the data model has been simplified.  While we are doing that, we will have an opportunity to simplify some of the transactions.
